name: RythmDart
version: 0.1.0
dependencies:
  unittest: any
  petitparser:
    git: https://github.com/freewind/PetitParserDart.git
#    path: /Users/freewind/dev/github/PetitParserDart
  pathos: any
